[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
testnet = "${TESTNET_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
testnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
